In [55]:
import pandas as pd
import sklearn
import numpy as np
df1=pd.read_csv("News_articles_dataset.csv",parse_dates=["Date"])
df2=pd.read_csv("HistoricalData_1623748350213.csv",parse_dates=["Date"])

In [56]:

df1.isnull().sum()

Date         0
Headlines    0
dtype: int64

In [57]:
df1.sort_index(inplace=True)

In [58]:
df1.head()

Date                                          Headlines
0 2015-01-01  What Can We Expect From Apple Inc. In 2015? 1 ...
1 2015-02-01  What to expect from Apple in 2015 beyond its s...
2 2015-03-01  Mountie: An inexpensive and innovative way to ...
3 2015-04-01  Donald Yacktman on the Sources of Moats, His C...
4 2015-05-01  SIM-free iPhone 6, 6 Plus reportedly debuting ...

In [59]:
df2.head()

Date Close/Last    Volume     Open     High        Low
0 2021-06-14    $130.48  96906490  $127.82  $130.54    $127.07
1 2021-06-11    $127.35  53522370  $126.53  $127.44     $126.1
2 2021-06-10    $126.11  71186420  $127.02  $128.19    $125.94
3 2021-06-09    $127.13  56877940  $127.21  $127.75    $126.52
4 2021-06-08    $126.74  74403770   $126.6  $128.46  $126.2101

In [60]:
df2.sort_values('Date',inplace=True)

In [61]:
df2.reset_index()

index       Date Close/Last     Volume      Open      High        Low
0      2515 2011-06-15   $11.6696  395841722  $11.7768  $11.7964   $11.6029
1      2514 2011-06-16   $11.6129  507299317   $11.675  $11.7386   $11.3689
2      2513 2011-06-17   $11.4379  614859874  $11.7496  $11.7589   $11.4057
3      2512 2011-06-20   $11.2614  639595904  $11.3341  $11.3464   $11.0893
4      2511 2011-06-21   $11.6179  492451483    $11.31  $11.6357   $11.2571
...     ...        ...        ...        ...       ...       ...        ...
2511      4 2021-06-08    $126.74   74403770    $126.6   $128.46  $126.2101
2512      3 2021-06-09    $127.13   56877940   $127.21   $127.75    $126.52
2513      2 2021-06-10    $126.11   71186420   $127.02   $128.19    $125.94
2514      1 2021-06-11    $127.35   53522370   $126.53   $127.44     $126.1
2515      0 2021-06-14    $130.48   96906490   $127.82   $130.54    $127.07

[2516 rows x 7 columns]

In [62]:
a=pd.merge(df1,df2,how='inner',on=['Date'])

a.index=a['Date']

In [63]:
a["Close/Last"]=a["Close/Last"].str.replace('$', '').astype(float)
a["Open"]=a["Open"].str.replace('$', '').astype(float)
a["High"]=a["High"].str.replace('$', '').astype(float)
a["Low"]=a["Low"].str.replace('$', '').astype(float)

In [64]:
a.head()


Date                                          Headlines  \
Date                                                                       
2015-04-01 2015-04-01  Donald Yacktman on the Sources of Moats, His C...   
2015-05-01 2015-05-01  SIM-free iPhone 6, 6 Plus reportedly debuting ...   
2015-06-01 2015-06-01  Technology Transforming Cars Into "Phones On W...   
2015-07-01 2015-07-01  Apple issues fourth developer beta of OS X 10....   
2015-09-01 2015-09-01  Samsung is reportedly making a secret new chip...   

            Close/Last     Volume     Open     High      Low  
Date                                                          
2015-04-01     31.0625  161852560  31.2050  31.2800  30.7750  
2015-05-01     32.2375  229396000  31.5250  32.5325  31.3250  
2015-06-01     32.6337  128064080  32.8000  32.8475  32.5125  
2015-07-01     31.6500  120827560  31.7250  31.7350  31.4975  
2015-09-01     26.9300  306248680  27.5375  27.9700  26.8400

In [65]:
a.drop('Date',axis=1,inplace=True)

In [66]:
a.head()

Headlines  Close/Last  \
Date                                                                        
2015-04-01  Donald Yacktman on the Sources of Moats, His C...     31.0625   
2015-05-01  SIM-free iPhone 6, 6 Plus reportedly debuting ...     32.2375   
2015-06-01  Technology Transforming Cars Into "Phones On W...     32.6337   
2015-07-01  Apple issues fourth developer beta of OS X 10....     31.6500   
2015-09-01  Samsung is reportedly making a secret new chip...     26.9300   

               Volume     Open     High      Low  
Date                                              
2015-04-01  161852560  31.2050  31.2800  30.7750  
2015-05-01  229396000  31.5250  32.5325  31.3250  
2015-06-01  128064080  32.8000  32.8475  32.5125  
2015-07-01  120827560  31.7250  31.7350  31.4975  
2015-09-01  306248680  27.5375  27.9700  26.8400

In [67]:
a['close_price'] = a['Close/Last'].shift(1) 

In [68]:
a['closed_price_diff']=''
a['closed_price_diff']=a['Close/Last']-a['close_price']

In [69]:
a.head()

Headlines  Close/Last  \
Date                                                                        
2015-04-01  Donald Yacktman on the Sources of Moats, His C...     31.0625   
2015-05-01  SIM-free iPhone 6, 6 Plus reportedly debuting ...     32.2375   
2015-06-01  Technology Transforming Cars Into "Phones On W...     32.6337   
2015-07-01  Apple issues fourth developer beta of OS X 10....     31.6500   
2015-09-01  Samsung is reportedly making a secret new chip...     26.9300   

               Volume     Open     High      Low  close_price  \
Date                                                            
2015-04-01  161852560  31.2050  31.2800  30.7750          NaN   
2015-05-01  229396000  31.5250  32.5325  31.3250      31.0625   
2015-06-01  128064080  32.8000  32.8475  32.5125      32.2375   
2015-07-01  120827560  31.7250  31.7350  31.4975      32.6337   
2015-09-01  306248680  27.5375  27.9700  26.8400      31.6500   

            closed_price_diff  
Date                           
2015-04-01                NaN  
2015-05-01             1.1750  
2015-06-01             0.3962  
2015-07-01            -0.9837  
2015-09-01            -4.7200

In [70]:
a['profit/loss']=''
a['profit/loss'] = a['closed_price_diff'].apply(lambda x: 1 if x>0 else 0)

In [71]:
a.head()

Headlines  Close/Last  \
Date                                                                        
2015-04-01  Donald Yacktman on the Sources of Moats, His C...     31.0625   
2015-05-01  SIM-free iPhone 6, 6 Plus reportedly debuting ...     32.2375   
2015-06-01  Technology Transforming Cars Into "Phones On W...     32.6337   
2015-07-01  Apple issues fourth developer beta of OS X 10....     31.6500   
2015-09-01  Samsung is reportedly making a secret new chip...     26.9300   

               Volume     Open     High      Low  close_price  \
Date                                                            
2015-04-01  161852560  31.2050  31.2800  30.7750          NaN   
2015-05-01  229396000  31.5250  32.5325  31.3250      31.0625   
2015-06-01  128064080  32.8000  32.8475  32.5125      32.2375   
2015-07-01  120827560  31.7250  31.7350  31.4975      32.6337   
2015-09-01  306248680  27.5375  27.9700  26.8400      31.6500   

            closed_price_diff  profit/loss  
Date                                        
2015-04-01                NaN            0  
2015-05-01             1.1750            1  
2015-06-01             0.3962            1  
2015-07-01            -0.9837            0  
2015-09-01            -4.7200            0

In [73]:
a.drop(['Open','Low','High','Volume','Close/Last','close_price','closed_price_diff'],axis=1,inplace=True)

In [74]:
a.head()

Headlines  profit/loss
Date                                                                      
2015-04-01  Donald Yacktman on the Sources of Moats, His C...            0
2015-05-01  SIM-free iPhone 6, 6 Plus reportedly debuting ...            1
2015-06-01  Technology Transforming Cars Into "Phones On W...            1
2015-07-01  Apple issues fourth developer beta of OS X 10....            0
2015-09-01  Samsung is reportedly making a secret new chip...            0

In [75]:
import nltk
from nltk.corpus import stopwords
import string
def text_cleaning(a):
    remove_punctuation=[char for char in a if char not in string.punctuation]
    remove_punctuation=''.join(remove_punctuation)
    return [word for word in remove_punctuation.split() if word.lower() not in stopwords.words('english')]

In [76]:
print(a.iloc[:,0].apply(text_cleaning))

Date
2015-04-01    [Donald, Yacktman, Sources, Moats, Concern, Ap...
2015-05-01    [SIMfree, iPhone, 6, 6, Plus, reportedly, debu...
2015-06-01    [Technology, Transforming, Cars, Phones, Wheel...
2015-07-01    [Apple, issues, fourth, developer, beta, OS, X...
2015-09-01    [Samsung, reportedly, making, secret, new, chi...
                                    ...                        
2021-05-28    [Apple, pushes, back, launch, podcast, subscri...
2021-01-06    [Judge, dismisses, charges, Apple, security, c...
2021-04-06    [Global, equities, nearly, grasp, alltime, rec...
2021-05-06    [Apple, employees, want, remotework, flexibili...
2021-06-14    [Cramers, Mad, Money, Recap, FAANG, Microsoft,...
Name: Headlines, Length: 1596, dtype: object


In [77]:
from sklearn.feature_extraction.text import CountVectorizer
c_vectorizer=CountVectorizer(analyzer=text_cleaning).fit(a['Headlines'])

c_vectorizer.vocabulary_

{'Donald': 12797,
 'Yacktman': 36094,
 'Sources': 30761,
 'Moats': 22339,
 'Concern': 10656,
 'Applequots': 6227,
 'Strategy': 31414,
 'first': 41011,
 'great': 41631,
 'Apple': 6098,
 'Watch': 35268,
 'accessory': 36427,
 'CES': 8856,
 'New': 23628,
 'Seagate': 29536,
 'drive': 40006,
 'streams': 50455,
 'content': 38850,
 'Chromecast': 10008,
 'TV': 32185,
 'Tech': 32430,
 'Emerge': 13672,
 '2015': 1543,
 'LG': 19887,
 'Galaxy': 15984,
 'S6': 28743,
 'Kodak': 19762,
 'Smartphone': 30489,
 'Inc': 18334,
 'AAPL': 4468,
 'Facing': 14662,
 'Class': 10136,
 'Action': 5102,
 'Lawsuit': 20180,
 'Falsely': 14730,
 'Advertising': 5263,
 'iPhone': 42294,
 'iPad': 42276,
 'Storage': 31358,
 'Capacity': 9327,
 'Unexpected': 34104,
 'Trends': 33414,
 '6': 3524,
 'Sales': 29178,
 'Continue': 10857,
 'Propel': 26585,
 'iBeaconquots': 42199,
 'Hardware': 17065,
 'Specifications': 30844,
 'Published': 26687,
 'FCC': 14448,
 'Hacking': 16911,
 'Tool': 33095,
 'Claims': 10112,
 'Breach': 8314,
 'iCloud

In [78]:
headlines_c=c_vectorizer.transform(a['Headlines'])
print(headlines_c)

  (0, 1543)	6
  (0, 3524)	1
  (0, 4468)	4
  (0, 4491)	1
  (0, 5102)	1
  (0, 5263)	1
  (0, 5451)	1
  (0, 6098)	11
  (0, 6227)	2
  (0, 8314)	1
  (0, 8856)	2
  (0, 9327)	1
  (0, 10008)	1
  (0, 10112)	1
  (0, 10136)	1
  (0, 10279)	1
  (0, 10656)	1
  (0, 10857)	1
  (0, 12520)	1
  (0, 12797)	1
  (0, 13672)	1
  (0, 14245)	1
  (0, 14448)	1
  (0, 14662)	1
  (0, 14730)	1
  :	:
  (1595, 50374)	1
  (1595, 50385)	2
  (1595, 50402)	1
  (1595, 50410)	3
  (1595, 50669)	1
  (1595, 50801)	1
  (1595, 50918)	1
  (1595, 50976)	2
  (1595, 51046)	1
  (1595, 51094)	1
  (1595, 51348)	1
  (1595, 51353)	1
  (1595, 51401)	1
  (1595, 51537)	1
  (1595, 51577)	1
  (1595, 51873)	1
  (1595, 51901)	1
  (1595, 51913)	1
  (1595, 51990)	1
  (1595, 52053)	1
  (1595, 52122)	1
  (1595, 52131)	2
  (1595, 52222)	3
  (1595, 52435)	1
  (1595, 52529)	2


In [79]:
X=headlines_c.toarray()
print(X)
X.shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(1596, 52583)

In [80]:
from sklearn.feature_extraction.text import TfidfTransformer
T_transformer=TfidfTransformer().fit(headlines_c)
print(T_transformer)


TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)


In [81]:
Headlines_T=T_transformer.transform(headlines_c)
print(Headlines_T)
print(Headlines_T.shape)

  (0, 50455)	0.14278115621961898
  (0, 42370)	0.13398837094434463
  (0, 42294)	0.06909026149464055
  (0, 42276)	0.03926445887721081
  (0, 42214)	0.09013379269993785
  (0, 42199)	0.1666053072054037
  (0, 41631)	0.09045506786156966
  (0, 41011)	0.052536562245264505
  (0, 40006)	0.09637237313517381
  (0, 38850)	0.09078117440937906
  (0, 36427)	0.11561414341748023
  (0, 36094)	0.1666053072054037
  (0, 35667)	0.15157394149489337
  (0, 35268)	0.08750331085374395
  (0, 34104)	0.1244069286927546
  (0, 33414)	0.07658719755359823
  (0, 33095)	0.09284804016134816
  (0, 32430)	0.02797410414736247
  (0, 32185)	0.043687523561615
  (0, 31414)	0.06914470105776782
  (0, 31358)	0.10058277770696991
  (0, 30844)	0.15781252193012932
  (0, 30771)	0.11016421995855993
  (0, 30761)	0.11667219114713287
  (0, 30679)	0.08010148853753925
  :	:
  (1595, 5145)	0.0414270051767497
  (1595, 5122)	0.035435708517590744
  (1595, 4702)	0.01686335432888953
  (1595, 4676)	0.03485068692704856
  (1595, 4606)	0.0206682350127084

In [84]:
y=a['profit/loss']

In [92]:
x_train = Headlines_T[:80]
y_train = y[:80]
x_test= Headlines_T[80:]
y_test= y[80:]

In [93]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()

In [94]:
model.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [95]:
y_pred=model.predict(x_test)

In [96]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [97]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.5224274406332454